// Code generated by aru model:build from model.go. DO NOT EDIT.

package llama

import (
	"context"
	"iter"

	"github.com/arandu-io/hesape/auth"
	"github.com/arandu-io/hesape/database/model"
	"github.com/arandu-io/hesape/database/query"
	"github.com/arandu-io/hesape/pagination"
)

// Llamas starts a query on the table of Llama, through db.
//
// Global scopes are on and, unless the table is Global, every statement is
// filtered by the tenant of the Grant its terminal takes.
func Llamas(db model.DB) *LlamaQuery { return &LlamaQuery{b: llamaTable.Query(db)} }

// LlamaQuery is a query on the table of Llama.
//
// The methods that build return the query, so they chain. The methods that run
// take a context and an auth.Grant, and return Llama rows or a value; there is
// no way to run one without a Grant.
type LlamaQuery struct{ b *model.Builder }

// Base returns the core builder the query forwards to. It is for code in this
// package -- a local scope in the custom block of model.go -- and for the
// factory, which builds rows through it.
func (q *LlamaQuery) Base() *model.Builder { return q.b }

// New returns an empty Llama on the query's connection, not yet saved, filled
// with what WithAttributes recorded on the query.
func (q *LlamaQuery) New() (*Llama, error) {
	e, err := q.b.NewModelInstance(nil)
	return llamaOf(e), err
}

// LlamaCollection is rows of Llama, as a query returns them.
type LlamaCollection []*Llama

// LlamaCollectionOf converts rows of the table of Llama. A nil input is a nil
// collection.
func LlamaCollectionOf(rows model.Rows) LlamaCollection {
	if rows == nil {
		return nil
	}
	out := make(LlamaCollection, len(rows))
	for i, e := range rows {
		out[i] = e.(*Llama)
	}
	return out
}

func llamaOf(e model.Entity) *Llama {
	row, _ := e.(*Llama)
	return row
}

// llamaColumn turns a closure over LlamaQuery into one over the core builder, so
// passing func(*LlamaQuery) where a column goes adds a parenthesised group.
func llamaColumn(column any) any {
	if group, ok := column.(func(*LlamaQuery)); ok {
		return func(b *model.Builder) { group(&LlamaQuery{b: b}) }
	}
	return column
}

// Clone returns an independent copy of the query.
func (q *LlamaQuery) Clone() *LlamaQuery { return &LlamaQuery{b: q.b.Clone()} }

// Where adds a where clause; a func(*LlamaQuery) in place of the column adds a group.
func (q *LlamaQuery) Where(column any, args ...any) *LlamaQuery {
	q.b.Where(llamaColumn(column), args...)
	return q
}

// OrWhere adds an or-where clause; a func(*LlamaQuery) in place of the column adds a group.
func (q *LlamaQuery) OrWhere(column any, args ...any) *LlamaQuery {
	q.b.OrWhere(llamaColumn(column), args...)
	return q
}

// WhereNot adds a negated where clause, or a negated group.
func (q *LlamaQuery) WhereNot(column any, args ...any) *LlamaQuery {
	q.b.WhereNot(llamaColumn(column), args...)
	return q
}

// OrWhereNot adds an or-joined negated where clause, or a negated group.
func (q *LlamaQuery) OrWhereNot(column any, args ...any) *LlamaQuery {
	q.b.OrWhereNot(llamaColumn(column), args...)
	return q
}

func (q *LlamaQuery) WhereIn(column any, values []any) *LlamaQuery {
	q.b.WhereIn(column, values)
	return q
}

func (q *LlamaQuery) WhereNotIn(column any, values []any) *LlamaQuery {
	q.b.WhereNotIn(column, values)
	return q
}

func (q *LlamaQuery) WhereNull(columns ...any) *LlamaQuery {
	q.b.WhereNull(columns...)
	return q
}

func (q *LlamaQuery) WhereNotNull(columns ...any) *LlamaQuery {
	q.b.WhereNotNull(columns...)
	return q
}

func (q *LlamaQuery) WhereBetween(column any, from, to any) *LlamaQuery {
	q.b.WhereBetween(column, from, to)
	return q
}

func (q *LlamaQuery) WhereColumn(first any, args ...any) *LlamaQuery {
	q.b.WhereColumn(first, args...)
	return q
}

func (q *LlamaQuery) WhereKey(id any) *LlamaQuery {
	q.b.WhereKey(id)
	return q
}

func (q *LlamaQuery) WhereExists(callback func(*query.Builder)) *LlamaQuery {
	q.b.WhereExists(callback)
	return q
}

func (q *LlamaQuery) WhereNotExists(callback func(*query.Builder)) *LlamaQuery {
	q.b.WhereNotExists(callback)
	return q
}

func (q *LlamaQuery) WhereHas(relation string, callback func(*query.Builder)) *LlamaQuery {
	q.b.WhereHas(relation, callback)
	return q
}

func (q *LlamaQuery) OrWhereHas(relation string, callback func(*query.Builder)) *LlamaQuery {
	q.b.OrWhereHas(relation, callback)
	return q
}

func (q *LlamaQuery) WhereDoesntHave(relation string, callback func(*query.Builder)) *LlamaQuery {
	q.b.WhereDoesntHave(relation, callback)
	return q
}

func (q *LlamaQuery) OrWhereDoesntHave(relation string, callback func(*query.Builder)) *LlamaQuery {
	q.b.OrWhereDoesntHave(relation, callback)
	return q
}

func (q *LlamaQuery) WhereRelation(relation string, column any, args ...any) *LlamaQuery {
	q.b.WhereRelation(relation, column, args...)
	return q
}

func (q *LlamaQuery) OrWhereRelation(relation string, column any, args ...any) *LlamaQuery {
	q.b.OrWhereRelation(relation, column, args...)
	return q
}

func (q *LlamaQuery) WhereHasCount(relation string, callback func(*query.Builder), operator string, count int) *LlamaQuery {
	q.b.WhereHasCount(relation, callback, operator, count)
	return q
}

func (q *LlamaQuery) WhereBelongsTo(relationshipName string, related ...model.Entity) *LlamaQuery {
	q.b.WhereBelongsTo(relationshipName, related...)
	return q
}

func (q *LlamaQuery) Has(relation, operator string, count int, boolean string, callback func(*query.Builder)) *LlamaQuery {
	q.b.Has(relation, operator, count, boolean, callback)
	return q
}

func (q *LlamaQuery) OrHas(relation, operator string, count int) *LlamaQuery {
	q.b.OrHas(relation, operator, count)
	return q
}

func (q *LlamaQuery) DoesntHave(relation, boolean string, callback func(*query.Builder)) *LlamaQuery {
	q.b.DoesntHave(relation, boolean, callback)
	return q
}

func (q *LlamaQuery) OrDoesntHave(relation string) *LlamaQuery {
	q.b.OrDoesntHave(relation)
	return q
}

func (q *LlamaQuery) Select(columns ...any) *LlamaQuery {
	q.b.Select(columns...)
	return q
}

func (q *LlamaQuery) AddSelect(columns ...any) *LlamaQuery {
	q.b.AddSelect(columns...)
	return q
}

func (q *LlamaQuery) SelectRaw(expression string, bindings ...any) *LlamaQuery {
	q.b.SelectRaw(expression, bindings...)
	return q
}

func (q *LlamaQuery) Join(table any, first any, args ...any) *LlamaQuery {
	q.b.Join(table, first, args...)
	return q
}

func (q *LlamaQuery) GroupBy(groups ...any) *LlamaQuery {
	q.b.GroupBy(groups...)
	return q
}

func (q *LlamaQuery) OrderBy(column any, direction ...string) *LlamaQuery {
	q.b.OrderBy(column, direction...)
	return q
}

func (q *LlamaQuery) OrderByDesc(column any) *LlamaQuery {
	q.b.OrderByDesc(column)
	return q
}

func (q *LlamaQuery) Latest(column ...string) *LlamaQuery {
	q.b.Latest(column...)
	return q
}

func (q *LlamaQuery) Oldest(column ...string) *LlamaQuery {
	q.b.Oldest(column...)
	return q
}

func (q *LlamaQuery) Limit(value int) *LlamaQuery {
	q.b.Limit(value)
	return q
}

func (q *LlamaQuery) Offset(value int) *LlamaQuery {
	q.b.Offset(value)
	return q
}

func (q *LlamaQuery) ForPage(page, perPage int) *LlamaQuery {
	q.b.ForPage(page, perPage)
	return q
}

func (q *LlamaQuery) With(relations ...string) *LlamaQuery {
	q.b.With(relations...)
	return q
}

func (q *LlamaQuery) WithCount(relations ...string) *LlamaQuery {
	q.b.WithCount(relations...)
	return q
}

func (q *LlamaQuery) WithExists(relation string) *LlamaQuery {
	q.b.WithExists(relation)
	return q
}

func (q *LlamaQuery) WithSum(relation, column string) *LlamaQuery {
	q.b.WithSum(relation, column)
	return q
}

func (q *LlamaQuery) WithAvg(relation, column string) *LlamaQuery {
	q.b.WithAvg(relation, column)
	return q
}

func (q *LlamaQuery) WithMin(relation, column string) *LlamaQuery {
	q.b.WithMin(relation, column)
	return q
}

func (q *LlamaQuery) WithMax(relation, column string) *LlamaQuery {
	q.b.WithMax(relation, column)
	return q
}

func (q *LlamaQuery) Without(relations ...string) *LlamaQuery {
	q.b.Without(relations...)
	return q
}

func (q *LlamaQuery) WithoutGlobalScope(identifier string) *LlamaQuery {
	q.b.WithoutGlobalScope(identifier)
	return q
}

func (q *LlamaQuery) WithoutGlobalScopes(identifiers ...string) *LlamaQuery {
	q.b.WithoutGlobalScopes(identifiers...)
	return q
}

// Get runs the query and returns the rows.
func (q *LlamaQuery) Get(ctx context.Context, g auth.Grant, columns ...any) (LlamaCollection, error) {
	rows, err := q.b.Get(ctx, g, columns...)
	return LlamaCollectionOf(rows), err
}

// First returns the first row, or nil and no error when there is none.
func (q *LlamaQuery) First(ctx context.Context, g auth.Grant, columns ...any) (*Llama, error) {
	e, err := q.b.First(ctx, g, columns...)
	return llamaOf(e), err
}

func (q *LlamaQuery) FirstOrFail(ctx context.Context, g auth.Grant, columns ...any) (*Llama, error) {
	e, err := q.b.FirstOrFail(ctx, g, columns...)
	return llamaOf(e), err
}

func (q *LlamaQuery) FirstWhere(ctx context.Context, g auth.Grant, column any, args ...any) (*Llama, error) {
	e, err := q.b.FirstWhere(ctx, g, column, args...)
	return llamaOf(e), err
}

func (q *LlamaQuery) FirstOrNew(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Llama, error) {
	e, err := q.b.FirstOrNew(ctx, g, attributes, values)
	return llamaOf(e), err
}

func (q *LlamaQuery) FirstOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Llama, error) {
	e, err := q.b.FirstOrCreate(ctx, g, attributes, values)
	return llamaOf(e), err
}

func (q *LlamaQuery) Find(ctx context.Context, g auth.Grant, id any, columns ...any) (*Llama, error) {
	e, err := q.b.Find(ctx, g, id, columns...)
	return llamaOf(e), err
}

func (q *LlamaQuery) FindOrFail(ctx context.Context, g auth.Grant, id any, columns ...any) (*Llama, error) {
	e, err := q.b.FindOrFail(ctx, g, id, columns...)
	return llamaOf(e), err
}

func (q *LlamaQuery) FindOrNew(ctx context.Context, g auth.Grant, id any, columns ...any) (*Llama, error) {
	e, err := q.b.FindOrNew(ctx, g, id, columns...)
	return llamaOf(e), err
}

func (q *LlamaQuery) FindMany(ctx context.Context, g auth.Grant, ids []any, columns ...any) (LlamaCollection, error) {
	rows, err := q.b.FindMany(ctx, g, ids, columns...)
	return LlamaCollectionOf(rows), err
}

func (q *LlamaQuery) Sole(ctx context.Context, g auth.Grant, columns ...any) (*Llama, error) {
	e, err := q.b.Sole(ctx, g, columns...)
	return llamaOf(e), err
}

func (q *LlamaQuery) Create(ctx context.Context, g auth.Grant, attributes map[string]any) (*Llama, error) {
	e, err := q.b.Create(ctx, g, attributes)
	return llamaOf(e), err
}

func (q *LlamaQuery) ForceCreate(ctx context.Context, g auth.Grant, attributes map[string]any) (*Llama, error) {
	e, err := q.b.ForceCreate(ctx, g, attributes)
	return llamaOf(e), err
}

func (q *LlamaQuery) UpdateOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Llama, error) {
	e, err := q.b.UpdateOrCreate(ctx, g, attributes, values)
	return llamaOf(e), err
}

func (q *LlamaQuery) Paginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (LlamaCollection, *pagination.LengthAwarePage, error) {
	rows, meta, err := q.b.Paginate(ctx, g, perPage, page, opts, columns...)
	return LlamaCollectionOf(rows), meta, err
}

func (q *LlamaQuery) SimplePaginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (LlamaCollection, *pagination.Page, error) {
	rows, meta, err := q.b.SimplePaginate(ctx, g, perPage, page, opts, columns...)
	return LlamaCollectionOf(rows), meta, err
}

func (q *LlamaQuery) CursorPaginate(ctx context.Context, g auth.Grant, perPage int, cursor *pagination.Cursor, opts pagination.Options, columns ...any) (LlamaCollection, *pagination.CursorPage, error) {
	rows, meta, err := q.b.CursorPaginate(ctx, g, perPage, cursor, opts, columns...)
	return LlamaCollectionOf(rows), meta, err
}

func (q *LlamaQuery) Chunk(ctx context.Context, g auth.Grant, count int, callback func(LlamaCollection, int) (bool, error)) error {
	return q.b.Chunk(ctx, g, count, func(rows model.Rows, page int) (bool, error) {
		return callback(LlamaCollectionOf(rows), page)
	})
}

func (q *LlamaQuery) Each(ctx context.Context, g auth.Grant, count int, callback func(*Llama, int) (bool, error)) error {
	return q.b.Each(ctx, g, count, func(e model.Entity, index int) (bool, error) {
		return callback(llamaOf(e), index)
	})
}

func (q *LlamaQuery) Cursor(ctx context.Context, g auth.Grant) iter.Seq2[*Llama, error] {
	return func(yield func(*Llama, error) bool) {
		for e, err := range q.b.Cursor(ctx, g) {
			if !yield(llamaOf(e), err) {
				return
			}
		}
	}
}

func (q *LlamaQuery) Count(ctx context.Context, g auth.Grant, columns ...any) (int64, error) {
	return q.b.Count(ctx, g, columns...)
}

func (q *LlamaQuery) Exists(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.Exists(ctx, g)
}

func (q *LlamaQuery) DoesntExist(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.DoesntExist(ctx, g)
}

func (q *LlamaQuery) Pluck(ctx context.Context, g auth.Grant, column string) ([]any, error) {
	return q.b.Pluck(ctx, g, column)
}

func (q *LlamaQuery) Value(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.Value(ctx, g, column)
}

func (q *LlamaQuery) ValueOrFail(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.ValueOrFail(ctx, g, column)
}

func (q *LlamaQuery) SoleValue(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.SoleValue(ctx, g, column)
}

func (q *LlamaQuery) Sum(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Sum(ctx, g, column)
}

func (q *LlamaQuery) Avg(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Avg(ctx, g, column)
}

func (q *LlamaQuery) Min(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Min(ctx, g, column)
}

func (q *LlamaQuery) Max(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Max(ctx, g, column)
}

func (q *LlamaQuery) Update(ctx context.Context, g auth.Grant, values map[string]any) (int64, error) {
	return q.b.Update(ctx, g, values)
}

func (q *LlamaQuery) Delete(ctx context.Context, g auth.Grant) (int64, error) {
	return q.b.Delete(ctx, g)
}

func (q *LlamaQuery) Increment(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Increment(ctx, g, column, amount, extra)
}

func (q *LlamaQuery) Decrement(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Decrement(ctx, g, column, amount, extra)
}

func (q *LlamaQuery) Insert(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.Insert(ctx, g, values...)
}

func (q *LlamaQuery) InsertOrIgnore(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.InsertOrIgnore(ctx, g, values...)
}

func (q *LlamaQuery) Upsert(ctx context.Context, g auth.Grant, values []map[string]any, uniqueBy, update []string) (int64, error) {
	return q.b.Upsert(ctx, g, values, uniqueBy, update)
}

func (q *LlamaQuery) Touch(ctx context.Context, g auth.Grant, column ...string) (int64, error) {
	return q.b.Touch(ctx, g, column...)
}

// Rows converts the collection back to the core's rows.
func (c LlamaCollection) Rows() model.Rows {
	out := make(model.Rows, len(c))
	for i, row := range c {
		out[i] = row
	}
	return out
}

func (c LlamaCollection) ModelKeys() []any { return c.Rows().ModelKeys() }

func (c LlamaCollection) Find(key any) *Llama { return llamaOf(c.Rows().Find(key)) }

func (c LlamaCollection) FindOrFail(key any) (*Llama, error) {
	e, err := c.Rows().FindOrFail(key)
	return llamaOf(e), err
}

func (c LlamaCollection) Contains(key any) bool { return c.Rows().Contains(key) }

func (c LlamaCollection) Pluck(column string) []any { return c.Rows().Pluck(column) }

func (c LlamaCollection) Only(keys ...any) LlamaCollection {
	return LlamaCollectionOf(c.Rows().Only(keys...))
}

func (c LlamaCollection) Except(keys ...any) LlamaCollection {
	return LlamaCollectionOf(c.Rows().Except(keys...))
}

func (c LlamaCollection) Unique() LlamaCollection { return LlamaCollectionOf(c.Rows().Unique()) }

func (c LlamaCollection) Load(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().Load(ctx, g, relations...)
}

func (c LlamaCollection) LoadMissing(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadMissing(ctx, g, relations...)
}

func (c LlamaCollection) LoadCount(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadCount(ctx, g, relations...)
}

func (c LlamaCollection) Fresh(ctx context.Context, g auth.Grant, with ...string) (LlamaCollection, error) {
	rows, err := c.Rows().Fresh(ctx, g, with...)
	return LlamaCollectionOf(rows), err
}

func (c LlamaCollection) ToArray() []map[string]any { return c.Rows().ToArray() }

// Fresh reads the row again, as a new Llama; it shadows the untyped one the
// embedded model promotes.
func (row *Llama) Fresh(ctx context.Context, g auth.Grant, with ...string) (*Llama, error) {
	e, err := row.Model.Fresh(ctx, g, with...)
	return llamaOf(e), err
}

// Replicate returns an unsaved copy of the row without its key; it shadows the
// untyped one the embedded model promotes.
func (row *Llama) Replicate(except ...string) (*Llama, error) {
	e, err := row.Model.Replicate(except...)
	return llamaOf(e), err
}
